name: quest
services:
  mongodb-service:
    image: 'mongo:8.0.3-noble'
    restart: always
    healthcheck:
      test: 'mongosh --quiet --eval "db.runCommand({ ping: 1 })" || exit 1'
      interval: 30s
      timeout: 5s
      retries: 3

  back:
    image: 'malinovskij/questionnaire-backend:v1'
    depends_on:
      mongodb-service:
        condition: service_healthy
        restart: true
    ports:
      - 3000:3000

  front:
    image: 'malinovskij/questionnaire-frontend:v2'
    ports:
      - 80:80
    depends_on:
      mongodb-service:
        condition: service_healthy
        restart: true