apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-app
  namespace: questionnaire-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back-app
          image: 'malinovskij/questionnaire-backend:v1'
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 1024Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "0.2"
---
kind: Service
apiVersion: v1
metadata:
  name: back-service
  namespace: questionnaire-namespace
spec:
  selector:
    app: back
  ports:
    - port: 3000