apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  namespace: questionnaire-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front-app
          image: 'malinovskij/questionnaire-frontend:v2'
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 1024Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "0.2"
---
kind: Service
apiVersion: v1
metadata:
  name: front-service
  namespace: questionnaire-namespace
spec:
  selector:
    app: front
  ports:
    - port: 80